---
# K3s configuration
k3s_version: "v1.36.4+k3s1"

k3s_server_url: "https://192.168.1.167:6443"

k3s_server_options:
  - "--disable=traefik"
  - "--disable=servicelb"
  - "--write-kubeconfig-mode=0644"
