all:
  children:

    control_plane:
      hosts:
        k8s-cp:
          ansible_host: 192.168.1.167

    workers:
      hosts:
        k8s-worker-1:
          ansible_host: 192.168.1.168
        k8s-worker-2:
          ansible_host: 192.168.1.169
        k8s-worker-3:
          ansible_host: 192.168.1.170

  vars:
    ansible_user: xcode
    ansible_python_interpreter: /usr/bin/python3
